# Generated by Django 5.0.6 on 2024-06-27 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
