# Generated by Django 5.0.6 on 2024-06-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_rename_completed_task_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
    ]
